-- All Work — run this in Supabase SQL Editor (safe to re-run)
-- Creates tables, profile/team triggers, RLS, and RPCs.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  display_name text,
  first_name text,
  last_name text,
  position text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role text check (role in ('owner', 'member')) default 'member',
  joined_at timestamp with time zone default now(),
  unique(team_id, user_id)
);

create table if not exists public.board_columns (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete cascade not null,
  name text not null,
  position int not null default 0,
  created_at timestamp with time zone default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text default 'todo',
  priority text default 'medium',
  due_date timestamp with time zone,
  team_id bigint references public.teams(id) on delete cascade,
  assignee_id uuid references public.profiles(id),
  created_at timestamp with time zone default now()
);

alter table public.tasks add column if not exists column_id bigint;
alter table public.tasks add column if not exists created_by uuid references public.profiles(id);

do $$
begin
  alter table public.tasks
    add constraint tasks_column_id_fkey
    foreign key (column_id) references public.board_columns(id) on delete restrict;
exception when duplicate_object then null;
end $$;

alter table public.tasks drop constraint if exists tasks_status_check;
alter table public.tasks drop constraint if exists tasks_priority_check;

do $$
begin
  alter table public.tasks add constraint tasks_priority_check
    check (priority in ('low', 'medium', 'high'));
exception when others then
  null;
end $$;

create index if not exists team_members_user_id_idx on public.team_members(user_id);
create index if not exists team_members_team_id_idx on public.team_members(team_id);
create index if not exists tasks_team_id_idx on public.tasks(team_id);
create index if not exists tasks_assignee_id_idx on public.tasks(assignee_id);
create index if not exists tasks_column_id_idx on public.tasks(column_id);
create index if not exists board_columns_team_id_idx on public.board_columns(team_id);
create index if not exists profiles_email_idx on public.profiles(email);

-- ---------------------------------------------------------------------------
-- Helpers (security definer — avoids RLS recursion)
-- ---------------------------------------------------------------------------
create or replace function public.is_team_member(tid bigint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.team_members
    where team_id = tid and user_id = auth.uid()
  );
$$;

create or replace function public.is_team_owner(tid bigint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.team_members
    where team_id = tid and user_id = auth.uid() and role = 'owner'
  );
$$;

create or replace function public.can_read_profile(pid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select pid = auth.uid()
  or exists (
    select 1
    from public.team_members tm
    join public.team_members me on me.team_id = tm.team_id
    where tm.user_id = pid and me.user_id = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, first_name, last_name, position)
  values (
    new.id,
    new.email,
    coalesce(
      nullif(trim(new.raw_user_meta_data->>'display_name'), ''),
      split_part(coalesce(new.email, ''), '@', 1)
    ),
    nullif(trim(new.raw_user_meta_data->>'first_name'), ''),
    nullif(trim(new.raw_user_meta_data->>'last_name'), ''),
    nullif(trim(new.raw_user_meta_data->>'position'), '')
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = coalesce(excluded.display_name, public.profiles.display_name),
    first_name = coalesce(excluded.first_name, public.profiles.first_name),
    last_name = coalesce(excluded.last_name, public.profiles.last_name),
    position = coalesce(excluded.position, public.profiles.position),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.handle_new_team()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  insert into public.team_members (team_id, user_id, role)
  values (new.id, auth.uid(), 'owner')
  on conflict (team_id, user_id) do nothing;

  insert into public.board_columns (team_id, name, position)
  select new.id, x.name, x.pos
  from (values ('To Do', 0), ('Doing', 1), ('Done', 2)) as x(name, pos)
  where not exists (
    select 1 from public.board_columns c where c.team_id = new.id
  );

  return new;
end;
$$;

drop trigger if exists on_team_created on public.teams;
create trigger on_team_created
  after insert on public.teams
  for each row execute function public.handle_new_team();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------
create or replace function public.invite_member_by_email(p_team_id bigint, p_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid;
begin
  if not public.is_team_owner(p_team_id) then
    raise exception 'Only the team owner can invite members';
  end if;

  select id into v_user
  from public.profiles
  where lower(email) = lower(trim(p_email));

  if v_user is null then
    raise exception 'User not found. They must sign up first.';
  end if;

  if v_user = auth.uid() then
    raise exception 'You are already in this team';
  end if;

  insert into public.team_members (team_id, user_id, role)
  values (p_team_id, v_user, 'member');
exception
  when unique_violation then
    raise exception 'This user is already a member';
end;
$$;

create or replace function public.leave_team(p_team_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
begin
  select role into v_role
  from public.team_members
  where team_id = p_team_id and user_id = auth.uid();

  if v_role is null then
    raise exception 'You are not a member of this team';
  end if;

  if v_role = 'owner' then
    raise exception 'Owner cannot leave. Delete the team instead.';
  end if;

  delete from public.team_members
  where team_id = p_team_id and user_id = auth.uid();
end;
$$;

grant execute on function public.is_team_member(bigint) to authenticated;
grant execute on function public.is_team_owner(bigint) to authenticated;
grant execute on function public.can_read_profile(uuid) to authenticated;
grant execute on function public.invite_member_by_email(bigint, text) to authenticated;
grant execute on function public.leave_team(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.tasks enable row level security;
alter table public.board_columns enable row level security;

drop policy if exists "profiles_select_self_or_teammates" on public.profiles;
create policy "profiles_select_self_or_teammates"
  on public.profiles for select
  to authenticated
  using (public.can_read_profile(id));

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  to authenticated
  with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "teams_select_members" on public.teams;
create policy "teams_select_members"
  on public.teams for select
  to authenticated
  using (public.is_team_member(id));

drop policy if exists "teams_insert_authenticated" on public.teams;
create policy "teams_insert_authenticated"
  on public.teams for insert
  to authenticated
  with check (auth.uid() is not null);

drop policy if exists "teams_update_owner" on public.teams;
create policy "teams_update_owner"
  on public.teams for update
  to authenticated
  using (public.is_team_owner(id));

drop policy if exists "teams_delete_owner" on public.teams;
create policy "teams_delete_owner"
  on public.teams for delete
  to authenticated
  using (public.is_team_owner(id));

drop policy if exists "team_members_select_members" on public.team_members;
create policy "team_members_select_members"
  on public.team_members for select
  to authenticated
  using (public.is_team_member(team_id));

drop policy if exists "team_members_insert_owner" on public.team_members;
create policy "team_members_insert_owner"
  on public.team_members for insert
  to authenticated
  with check (public.is_team_owner(team_id));

drop policy if exists "team_members_delete_owner_or_self" on public.team_members;
create policy "team_members_delete_owner_or_self"
  on public.team_members for delete
  to authenticated
  using (
    public.is_team_owner(team_id)
    or user_id = auth.uid()
  );

drop policy if exists "board_columns_select_members" on public.board_columns;
create policy "board_columns_select_members"
  on public.board_columns for select
  to authenticated
  using (public.is_team_member(team_id));

drop policy if exists "board_columns_insert_members" on public.board_columns;
create policy "board_columns_insert_members"
  on public.board_columns for insert
  to authenticated
  with check (public.is_team_member(team_id));

drop policy if exists "board_columns_update_members" on public.board_columns;
create policy "board_columns_update_members"
  on public.board_columns for update
  to authenticated
  using (public.is_team_member(team_id))
  with check (public.is_team_member(team_id));

drop policy if exists "board_columns_delete_members" on public.board_columns;
create policy "board_columns_delete_members"
  on public.board_columns for delete
  to authenticated
  using (public.is_team_member(team_id));

drop policy if exists "tasks_select_members" on public.tasks;
create policy "tasks_select_members"
  on public.tasks for select
  to authenticated
  using (public.is_team_member(team_id));

drop policy if exists "tasks_insert_members" on public.tasks;
create policy "tasks_insert_members"
  on public.tasks for insert
  to authenticated
  with check (public.is_team_member(team_id));

drop policy if exists "tasks_update_members" on public.tasks;
create policy "tasks_update_members"
  on public.tasks for update
  to authenticated
  using (public.is_team_member(team_id))
  with check (public.is_team_member(team_id));

drop policy if exists "tasks_delete_members" on public.tasks;
create policy "tasks_delete_members"
  on public.tasks for delete
  to authenticated
  using (public.is_team_member(team_id));

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
do $$
begin
  begin
    alter publication supabase_realtime add table public.tasks;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.teams;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.team_members;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.board_columns;
  exception when duplicate_object then null;
  end;
end $$;

-- Backfill default boards and attach existing tasks
insert into public.board_columns (team_id, name, position)
select t.id, x.name, x.pos
from public.teams t
cross join (values ('To Do', 0), ('Doing', 1), ('Done', 2)) as x(name, pos)
where not exists (
  select 1 from public.board_columns c where c.team_id = t.id
);

update public.tasks t
set column_id = c.id
from public.board_columns c
where t.column_id is null
  and c.team_id = t.team_id
  and c.position = case t.status
    when 'doing' then 1
    when 'done' then 2
    else 0
  end;

update public.tasks
set created_by = assignee_id
where created_by is null and assignee_id is not null;

-- Optional: if old teams have no members, assign an owner manually:
-- insert into public.team_members (team_id, user_id, role)
-- values (TEAM_ID, 'USER_UUID', 'owner');
